services:
  hideeseek-db:
    image: postgres:16
    container_name: hideeseek
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_users_data:/var/lib/postgresql/data
    env_file:
      - ./database/.env

volumes:
  db_users_data:
