name: HideSeek Deployement

on:
  push:
    branches: [ "main" ]

jobs:
  database:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./back
    env:
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "POSTGRES_DB=${POSTGRES_DB}" >> .env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
          echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
      - name: Start Database
        run: |
          docker-compose down --volumes --remove-orphans
          docker-compose up -d

  back:
    needs: database
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./back

    strategy:
      matrix:
        node-version: [ 18.19.0 ]
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      FRONT_URL: ${{secrets.FRONT_URL}}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'back/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: |
          npm run build
          pm2 start back
  
  front:
    needs: back
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./front
    
    strategy:
      matrix:
        node-version: [ 18.19.0 ]
    env:
      VITE_MAPBOX_STYLE_URL: ${{secrets.VITE_MAPBOX_STYLE_URL}}
      VITE_MAPBOX_TOKEN: ${{secrets.VITE_MAPBOX_TOKEN}}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            front
          sparse-checkout-cone-mode: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: |
          npm run build
          pm2 start front
